In [2]:
# ============== 综合案例 ==============
import sys
if "PyStudy_env" not in sys.executable:
    print("/n环境配置错误!!!/n")
    print(sys.executable)
else:
    print("环境配置正常")

环境配置正常

In [4]:
# 1. 导入库
import numpy  as np
import pandas as pd 
import matplotlib.pyplot as plt 
from matplotlib import rcParams 
rcParams['font.family'] = 'SimHei'
rcParams['axes.unicode_minus'] = False

In [31]:
# 2. 数据导入
df = pd.read_csv("./house_sales.csv")
df.head(2)

,city,address,area,floor,name,price,province,rooms,toward,unit,year,origin_url
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建,https://hf.esf.fang.com/chushou/3_404230646.htm
1,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建,https://hf.esf.fang.com/chushou/3_404230646.htm

In [24]:
# 3. 数据概览
# df.info()
df.head(2)

,city,address,area,floor,name,price,province,rooms,toward,unit,year
0,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建
1,合肥,龙岗-临泉东路和王岗大道交叉口东南角,90㎡,中层（共18层）,圣地亚哥,128万,安徽,3室2厅,南北向,14222元/㎡,2013年建

In [ ]:
# 4. 数据清洗
# 删去链接
try :
    df.drop(columns='origin_url' , inplace=True)
    print("成功删除网址栏")
except:
    print("已经删除网址栏")
# 检查缺失值
df.isna().sum()
# 删除年份
df.dropna(inplace=True)
# 
print

已经删除网址栏

city            0
address      1666
area          794
floor        2094
name          554
price         554
province        0
rooms        2082
toward        878
unit          554
year        48382
dtype: int64