In [ ]:
import sys
if "PyStudy_env" not in sys.executable:
    print("/n环境配置错误!!!/n")
    print(sys.executable)
else:
    print("环境配置正常")

环境配置正常

In [3]:
# Pandas
import numpy  as np
import pandas as pd

In [3]:
# ==================== 4. Pandas数据处理 ====================

In [ ]:
# 4-1 数据导入+导出
# 数据导入
df = pd.read_csv('../data/employees.csv')
print(type(df))
print(df.tail(2))
print(df.salary.mean())
# 数据导出
df = df.tail() # 抽样
# df.to_csv('new.csv')    # 导出

# json格式读取
df = pd.read_json('../data/data1.json')
print(type(df))
print(df)

# 复杂json读取
import json
with open('../data/test.json') as f:
    data = json.load(f)
print(type(data))
df = pd.DataFrame(data['users'])
print(df)

<class 'pandas.DataFrame'>
     employee_id first_name last_name     email  phone_number      job_id  \
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0
6461.682242990654
<class 'pandas.DataFrame'>
   id name  age
0   1   张三   25
1   2   李四   30
2   3   王五   28
<class 'dict'>
   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [ ]:
# 4-2 缺失值的处理
import pandas as pd
import numpy  as np

# 列举缺失值
s = pd.Series([1,2,np.nan,None,pd.NA])
df= pd.DataFrame([[1,pd.NA,2] , [2,3,4] , [None , 4 ,6 ]] , columns=['A' , "B" , 'C'])
# 查看缺失值
# print(s.isna())
# print(s.isnull())
print(df.isna())
print(df.isnull())
print(df.isna().sum(axis=1))    # 按照行查看缺失值的个数
print('-'*30)
# 处理缺失值
# 1. 剔除缺失值: 要注意,每一行对应的是采集的一次数据,而每一列只是数据的众多性质(列)中的一个
print(s.dropna())
print(df.dropna())          # 剔除的是一整条的记录
print(df.dropna(how="all")) # 所有的值都是缺失值才剔除这一行
print(df.dropna(thresh=3))  # 至少有n个值不是缺失值才保留
print(df.dropna(thresh=3,axis=1))  # 至少有n个值不是缺失值才保留 , 对列操作(axis = 0就对行操作)
print(df.dropna(subset=['A']))  # 只针对A列

       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    0
2    1
dtype: int64
------------------------------
   C
0  2
1  4
2  6
     A     B  C
0  1.0  <NA>  2
1  2.0     3  4

In [54]:
# 2. 填充缺失值
df = pd.read_csv('../data/weather_withna.csv')
print(df.head(3))
print(df.isna().sum().tail(2))
# 使用字典来填充
print(df.fillna({'temp_max':20}).tail(2))    
# 填充其他非NA数据的平均值
print(df.fillna(df['wind'].mean()).tail(2))
# 填充周边非NA数据
print(df.ffill().tail(2))    # 使用前面的数据填充
print(df.bfill().tail(2))    # 使用后面的数据填充

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
wind       303
weather    303
dtype: int64
            date  precipitation  temp_max  temp_min  wind weather
1459  2015-12-30            NaN      20.0       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation   temp_max  temp_min      wind   weather
1459  2015-12-30       3.242055   3.242055  3.242055  3.242055  3.242055
1460  2015-12-31      20.600000  12.200000  5.000000  3.800000      rain
            date  precipitation  temp_max  temp_min  wind weather
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [ ]:
# 4-3 重复数据处理
data = {
    'name': ['A' , "B" , 'A' , 'A'] ,
    "age" : [26,25,26,30],
    'city': ['NY' , 'LA' , "NY", 'CN'],
}
df = pd.DataFrame(data)
df.duplicated() # 检测一整条记录,全部一样就标记为重复,也就是根据行去重
df.drop_duplicates(subset=['name'])    # 根据指定列去重
df.drop_duplicates(subset=['name'] , keep='last')   # 根据指定列去重,相同情况保存最后一条

  name  age city
0    A   26   NY
1    B   25   LA
2    A   26   NY
3    A   30   CN

  name  age city
1    B   25   LA
3    A   30   CN

In [ ]:
# 4-4 数据类型转换
df = pd.read_csv('../data/sleep.csv')
df['age'] = df['age'].astype('int16')
# df['gender'] = df['gender'].astype('category')                # 类别有限,可以进行分类
df['gender'] = df['gender'].map({'Female':True , 'Male':False}) # 类别二元,可以直接map字典映射为bool
df.dtypes

person_id                    int64
gender                        bool
age                          int16
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [ ]:
# 4-5 数据变形
data = {
    'ID':[1,2],
    'name':['A haha' , "B haha"],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89],
}
df = pd.DataFrame(data)

df.T    # 转置
# 宽表转换成长表
# 解读:ID和name为自带属性不会变化,var_name为其他属性,共用一个名字列,value_name为其他属性共用的数据列
df2 = pd.melt(df,id_vars=['ID' , 'name'],var_name='科目',value_name='分数')   
df2.sort_values('name')

# 长表转换成宽表
pd.pivot(df2 , index=['ID' , 'name'] , columns='科目' , values='分数')

# 分列: expand扩展分列,必须要有!!!
# 例1 姓名空格分列
df[['first' , 'last']] = df['name'].str.split(' ' , expand=True)    # .str转为str 
# 例2 给blood_pressure分列
df = pd.read_csv('../data/sleep.csv')
df[['high' , 'low']] = df['blood_pressure'].str.split('/' , expand=True).astype('int16')
df.head(2)

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,high,low
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN,124,70
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN,131,86

In [ ]:
# 4-6 数据分箱 pd.<q>cut(x,bins,labels) bins:给数据分为n段区间,起始值和结束值为min和max
import pandas as pd
df = pd.read_csv('../data/employees.csv')
df1 = df.head(10)[['employee_id' , 'salary']]
# print(df1)
# 分箱(其实就是某列数据分区间)
pd.cut(df1['salary'] , bins = 3)    # 区间分隔值
df1['收入范围'] = pd.cut(df1['salary'] , bins=[0,10000,20000,30000],labels=['低','中','高'])  # 手动配置区间
pd.qcut(df1['salary'] , 3)   # 等距分隔(等人数/...)

# 例:对睡眠质量进行分箱评估
df = pd.read_csv('../data/sleep.csv')
df['睡眠质量'] = pd.cut(df.sleep_quality , bins=3 , labels=['低' , '中' , '高'])

# 对分箱的类别就是category
# str -> 类别 -> 统计
# 数值-> 分箱  -> 统计 , 都是category

# 重命名
data = {
    'name': ['A' , "B" , 'A' , 'A'] ,
    "age" : [26,25,26,30],
    'city': ['NY' , 'LA' , "NY", 'CN'],
}
df = pd.DataFrame(data)
# df.set_index('name')    # 将某一列设为索引
df = df.rename(columns={'age':"年龄"},index={0:4})   # 也是使用字典进行rename(列名或者序列号)
print(df.at[4,'年龄'])

26

In [ ]:
# 4-7 时间数据的处理
import pandas as pd 
# 性质
d = pd.Timestamp('2015-05-02 10:22')
print(d)
print(type(d))
print("年:" , d.year)
print("月:" , d.month)
print("日:" , d.day)
print(d.hour , d.minute , d.second , d.quarter) # 最后一个是季度
print("是否是月底:" , d.is_month_end)
# 方法
print('星期几:' , d.day_name())
print('转换为天' , d.to_period("D"))    # 转换为季度:"Q" , 年度:"Y" , 月度:"M" , 周:"W"

2015-05-02 10:22:00
<class 'pandas.Timestamp'>
年: 2015
月: 5
日: 2
10 22 0 2
是否是月底: False
星期几: Saturday
转换为天 2015-05-02

In [ ]:
# 字符串转换为日期类型
a = pd.to_datetime('20150228')
print(a)
print(type(a))

# DF 日期转换
df = pd.DataFrame(
    {
        'sales':[100,200,300],
        'date' :['20250601' , '20250602', '20250603']
    }
)
df['date'] = pd.to_datetime(df['date'])
df['week'] = df['date'].dt.day_name()   # dt强转,才能进行.day_name()

2015-02-28 00:00:00
<class 'pandas.Timestamp'>

   sales       date     week
0    100 2025-06-01   Sunday
1    200 2025-06-02   Monday
2    300 2025-06-03  Tuesday

In [ ]:
# csv日期转换
df = pd.read_csv('../data/weather.csv') 
df['datetime'] = pd.to_datetime(df['date']).dt.day_name()   # 把字符串转换为日期,依然dt强转

# 日期数据作为索引 适合后续切片
df.set_index('date' , inplace=True)
print(df.loc['2013-01':'2013-02'])  

# 时间间隔
d1 = pd.Timestamp('2026-03-01')
d2 = pd.Timestamp('2026-07-06')
print(d2 - d1)

# 创建时间序列
days = pd.date_range('2025-07-03' , '2026-02-09' , freq="W")    # 知道始终
days = pd.date_range('2025-07-03' , periods=10 , freq="W")      # 只知道起始和时长
print(type(days[0]))

127 days 00:00:00
<class 'pandas.Timestamp'>

DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07', '2025-09-14', '2025-09-21',
               '2025-09-28', '2025-10-05', '2025-10-12', '2025-10-19',
               '2025-10-26', '2025-11-02', '2025-11-09', '2025-11-16',
               '2025-11-23', '2025-11-30', '2025-12-07', '2025-12-14',
               '2025-12-21', '2025-12-28', '2026-01-04', '2026-01-11',
               '2026-01-18', '2026-01-25', '2026-02-01', '2026-02-08'],
              dtype='datetime64[us]', freq='W-SUN')

In [ ]:
# 4-8 分组聚合(统计) 先分组再统计
# df.groupby('分组的字段)['聚合的字段'].聚合函数(sum , mean等)
import pandas as pd 
df = pd.read_csv('../data/employees.csv')

# 数据预处理
# id填充(也可以删去)
df['department_id'] = df.department_id.ffill()
# 员工id float转为int
df['department_id'] = df['department_id'].astype('int64')

# 数据处理(分组聚合还可以多个参数)
df.groupby('department_id').groups  # 根据department_id进行分组,同一个组的department_id相同,组内是序列号
df.groupby('department_id').get_group(90)   # 查看具体的某个分组数据
df2 = df.groupby('department_id')[['salary']].mean().round(2)  # 先根据department_id分组,再围绕salary进行同组数据处理
df2.sort_values('salary')

                 salary
department_id
50              3475.56
30              4150.00
10              4400.00
60              5760.00
40              6500.00
100             8600.00
80              8900.00
20              9500.00
70             10000.00
110            10150.00
90             19333.33

In [ ]:
# 案例1 企鹅数据分析
# 1. 导入必要的库
import pandas as pd 
# 2. 导入数据
df = pd.read_csv('../data/penguins.csv')
df.head()
# df.info()
# 3. 数据清洗
# 缺失值检查
df.dropna(inplace=True) # 直接去除缺失值
df.isna().sum()
# 4. 数据特征的构造
# 4-1 性别数据类型转换
# df['sex'] = df['sex'].map({"Male":True , "Female":False}) # 第一种:bool值
df['sex'] = df['sex'].astype('category')   # 第二种:category
# 4-2 比例
df['bill_ratio'] = df['bill_length_mm'] / df['bill_depth_mm']
# 5. 数据分析
# 体重数据分箱
labels = ['低' , '中' , '高']
df['体重'] = pd.cut(df['body_mass_g'] , bins=3 , labels=labels)
# 按照岛屿分析体重(分组聚合)
df.groupby('island')['体重'].value_counts()

island     体重
Biscoe     中     78
           高     55
           低     30
Dream      低     86
           中     37
           高      0
Torgersen  低     34
           中     13
           高      0
Name: count, dtype: int64

In [ ]:
# 案例2 睡眠质量分析
# 1. 导入必要的库
import pandas as pd 
# 2. 导入数据
df = pd.read_csv('../data/sleep.csv')
# df.head()
# df.info()

# 3. 数据清洗
# 缺失值检查
df.isna().value_counts()
df.drop(columns='sleep_disorder' , inplace=True)    # 直接删除大量缺失的sleep_disorder列
# 4. 数据特征的构造
# 数据类型转换
df['gender'] = df['gender'].astype('category')
df['occupation'] = df['occupation'].astype('category')
df['bmi_category'] = df['bmi_category'].astype('category')
# 数据分列
df[['high' , 'low']] = df['blood_pressure'].str.split("/" , expand=True)
# 数据分箱:睡眠质量 + 年龄
df['睡眠质量'] = pd.cut(df['sleep_quality'] , bins = 3 , labels=['差' , '中' , '优'])
df['age'] = pd.cut(df['age'] , bins = 3 , labels=['青年' , '中年' , '老年'])
# 5. 数据统计,分析
# 查看BMI分布
df.groupby('bmi_category').agg({
    'sleep_duration' : 'mean',
    'sleep_quality' : 'mean',
    'stress_level' : 'mean',
})

# df.info()
# df.head()

              sleep_duration  sleep_quality  stress_level
bmi_category
Normal              7.794505       6.342857      4.857143
Obese               8.072449       6.189796      5.765306
Overweight          8.274312       6.101835      5.642202
Underweight         7.982353       5.896078      5.558824